# Generated by Django 4.2.7 on 2024-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_grupo', models.CharField(max_length=255)),
                ('descricao_grupo', models.TextField()),
                ('imagem_grupo', models.ImageField(upload_to='grupo_imagens/')),
                ('qtd_membros', models.IntegerField(default=0)),
                ('qtd_membros_total', models.IntegerField(default=100)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
