# Generated by Django 4.2.7 on 2024-05-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='imagem_grupo',
            field=models.URLField(),
        ),
    ]
