# Generated by Django 4.2.7 on 2024-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_imagem_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='qtd_membros',
        ),
        migrations.AlterField(
            model_name='main',
            name='imagem_grupo',
            field=models.ImageField(upload_to='grupo_imagens/'),
        ),
    ]
