# Generated by Django 4.2.7 on 2024-05-14 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_main_qtd_membros_alter_main_imagem_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='imagem_grupo',
            field=models.ImageField(upload_to='../main/static/imgs/grupo_imagens/'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.main')),
            ],
        ),
    ]
