# Generated by Django 4.2.7 on 2024-05-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_imagem_grupo_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='texto',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='autor',
        ),
    ]
