# Generated by Django 4.2.7 on 2024-05-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_texto_mensagem_conteudo_remove_mensagem_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.CharField(default='Sistema', max_length=100),
        ),
    ]
